name: base
channels:
  - conda-forge
dependencies:
  - archspec=0.2.3
  - boltons=24.0.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.28.1
  - ca-certificates=2024.2.2
  - certifi=2024.2.2
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - conda=24.3.0
  - conda-libmamba-solver=24.1.0
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - distro=1.9.0
  - fmt=10.2.1
  - icu=73.2
  - idna=3.6
  - jsonpatch=1.33
  - jsonpointer=2.4
  - krb5=1.21.2
  - libarchive=3.7.2
  - libcurl=8.7.1
  - libcxx=16.0.6
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libiconv=1.17
  - libmamba=1.5.8
  - libmambapy=1.5.8
  - libnghttp2=1.58.0
  - libsolv=0.7.28
  - libsqlite=3.45.2
  - libssh2=1.11.0
  - libxml2=2.12.6
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - lzo=2.10
  - mamba=1.5.8
  - menuinst=2.0.2
  - ncurses=6.4.20240210
  - openssl=3.2.1
  - packaging=24.0
  - pip=24.0
  - platformdirs=4.2.0
  - pluggy=1.4.0
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.10.14
  - python_abi=3.10
  - readline=8.2
  - reproc=14.2.4.post0
  - reproc-cpp=14.2.4.post0
  - requests=2.31.0
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - setuptools=69.5.1
  - tk=8.6.13
  - tqdm=4.66.2
  - truststore=0.8.0
  - tzdata=2024a
  - urllib3=2.2.1
  - wheel=0.43.0
  - xz=5.2.6
  - yaml-cpp=0.8.0
  - zstandard=0.22.0
  - zstd=1.5.5
  - pip:
      - babel==2.17.0
      - blinker==1.9.0
      - click==8.1.8
      - contourpy==1.3.0
      - cycler==0.12.1
      - duckdb==1.2.1
      - filelock==3.16.1
      - flask==3.1.0
      - flask-babel==4.0.0
      - fonttools==4.54.1
      - fsspec==2024.10.0
      - imageio==2.36.0
      - itsdangerous==2.2.0
      - jinja2==3.1.4
      - kiwisolver==1.4.7
      - lazy-loader==0.4
      - markupsafe==3.0.2
      - mpmath==1.3.0
      - networkx==3.4.2
      - numpy==2.1.2
      - pillow==11.0.0
      - protobuf==5.28.3
      - pyasn1==0.6.1
      - pyparsing==3.2.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.1
      - rsa==4.9
      - six==1.16.0
      - sympy==1.13.1
      - tifffile==2024.9.20
      - typing-extensions==4.12.2
      - werkzeug==3.1.3
